repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.0
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix, --config=ruff.toml ]
    # Run the formatter.
    - id: ruff-format
      args: [--config=ruff.toml ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0  # or latest
  hooks:
    - id: mypy
      args: [--strict]
